// <auto-generated />
using KotaAndShisanyamaHub.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KotaAndShisanyamaHub.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KotaAndShisanyamaHub.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat, mauris ut faucibus rhoncus, tellus orci blandit libero, a fermentum sem diam sagittis lacus. Proin.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Shisanyama Plater",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Entre",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat, mauris ut faucibus rhoncus, tellus orci blandit libero, a fermentum sem diam sagittis lacus. Proin.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Regular Platter",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Meal",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat, mauris ut faucibus rhoncus, tellus orci blandit libero, a fermentum sem diam sagittis lacus. Proin.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "BunnyChow Latte",
                            Price = 109.98999999999999
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dessert",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat, mauris ut faucibus rhoncus, tellus orci blandit libero, a fermentum sem diam sagittis lacus. Proin.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Sweet Pie",
                            Price = 65.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
